### ISSUE TITLE
So you just made a fancy ui wrapper on top of whisky's engine?

### ISSUE THREAD

**Issue by Mergemat** [MythicApp/Mythic#83]
do you consider adding something on top of it, or i just downloaded a game picker? what's the diff between mythic and heroic+whisky?

**Comment by jeremybosma** [comment]
Mythic is a game launcher aiming to have multiple mainstream launchers like steam, epic games, gog and more to play their windows games on macos

**Comment by blackxfiied** [comment]
> Mythic

> Heroic + Whisky

Heroic is, in fact, a gaming-oriented launcher built using a slower backend than Mythic and a subjectively less streamlined user interface.
Whisky makes it simple for you to use WhiskyWine (game porting toolkit with a few extra patches) and manually install whatever you'd like.
Mythic is a gaming-oriented launcher that unifies both of their functions. (And for now, it also uses the aforementioned WhiskyWine, which is OSS anyway)

And yeah! Mythic's goal since forever has been to also integrate steam natively into the launcher.
This is awaiting implementation, I've just been smoothing some rough edges with Mythic.

But at the end of the day, a "game picker" is fundamentally what all of these apps are.

**Comment by Mergemat** [comment]
ok, thanks for the answer!
